BEGIN;

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(64) NOT NULL,
    email VARCHAR(320) NOT NULL,
    image_url TEXT,
    create_by BIGINT NOT NULL,
    update_by BIGINT NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_delete SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_app_users PRIMARY KEY (id),
    CONSTRAINT ck_app_users_is_delete CHECK (is_delete IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_app_users_email_active
ON app_users(email)
WHERE is_delete = 0;

COMMENT ON TABLE app_users IS 'Application user accounts';
COMMENT ON COLUMN app_users.nickname IS 'Required user nickname';
COMMENT ON COLUMN app_users.email IS 'Normalized login email address';
COMMENT ON COLUMN app_users.image_url IS 'Optional user image URL';
COMMENT ON COLUMN app_users.create_by IS 'Creator user or service ID';
COMMENT ON COLUMN app_users.update_by IS 'Last updater user or service ID';
COMMENT ON COLUMN app_users.create_time IS 'Record creation time';
COMMENT ON COLUMN app_users.update_time IS 'Last record update time';
COMMENT ON COLUMN app_users.is_delete IS 'Logical deletion: 0 active, 1 deleted';

COMMIT;
